#!/bin/sh
export PATH="$PATH:/usr/local/bin"

mount -t devtmpfs /dev
# i do not know why but it refuses to do this shit by itself
#maybe because you dont have an init system genius
#mkdir /dev/pts /dev/shm
#mount -t devpts /dev/pts
#mount -t tmpfs /dev/shm
#mount -t proc /proc
#mount -t sysfs /sys
mkdir /sys/fs/cgroup

#mount -t tmpfs cgroup_root /sys/fs/cgroup
mount -t cgroup /sys/fs/cgroup
mount -t tmpfs /run
mount -t proc proc /proc
#mount -t sysfs sysfs /sys
#mount -t devtmpfs devtmpfs /dev
#mkdir -p /dev/pts /dev/shm
#mount -t devpts devpts /dev/pts
#mount -t tmpfs tmpfs /run

# dmesg -n 1

# figlet "Welcome to POPPYCROW LINUX"
echo "You are dropped into the debugging shell."
echo "Dinit supposedly works but doesn't drop you into a shell. (well i forcibly interrupt it to give you a shell) When you feel like you fixed it in this session, run exit"
/bin/sh
(
    sleep 5

    echo "dinit poop" > /dev/ttyS0

    echo "list of all " > /dev/ttyS0
    dinitctl list > /dev/ttyS0 2>&1

    echo "login.target" > /dev/ttyS0
    dinitctl status login.target > /dev/ttyS0 2>&1

    echo "pre-network.target" > /dev/ttyS0
    dinitctl status pre-network.target > /dev/ttyS0 2>&1

    echo "network.target" > /dev/ttyS0
    dinitctl status network.target > /dev/ttyS0 2>&1

    echo "system" > /dev/ttyS0
    dinitctl status system > /dev/ttyS0 2>&1

    echo "boot" > /dev/ttyS0
    dinitctl status boot > /dev/ttyS0 2>&1

    echo "agetty" > /dev/ttyS0
    dinitctl status agetty > /dev/ttyS0 2>&1
) &

exec /init_poppy
