#!/bin/sh

export PATH="$PATH:/bin:/sbin:/usr/sbin"

echo 'hello from poppy crow'
/bin/sh

# mount -t devtmpfs /dev
# # i do not know why but it refuses to do this shit by itself
# mkdir /dev/pts /dev/shm
# mount -t devpts /dev/pts
# mount -t tmpfs /dev/shm
# mount -t proc /proc
# mount -t sysfs /sys
# mkdir /sys/fs/cgroup
# mount -t cgroup /sys/fs/cgroup
# mount -t tmpfs /run
# 
# dmesg -n 1