pkgname = "pcre2"
pkgver = "10.47"
pkgrel = 1
pkgdesc = "A library that implements Perl 5-style regular expressions. 2nd version"
url = "https://github.com/PCRE2Project/pcre2"
arch = "x86_64"
license = "BSD-3-Clause WITH PCRE2-exception" # techincally it's "BSD-2-Clause" and "BSD-3-Clause WITH PCRE2-exception" at the same time but idk

# https://github.com/PCRE2Project/pcre2/releases/download/pcre2-10.47/pcre2-10.47.tar.gz
sources = [f"{url}/releases/download/{pkgname}-{pkgver}/{pkgname}-{pkgver}.tar.gz"]

depends = ["bzip2", "glibc", "readline", "zlib"]
makedepends = ["git"]
optdepends = ["sh"]





def build(c):
    c.SRCDIR = c.SRCDIR + f"/{pkgname}-{pkgver}"

    #c.sh("git submodule init")
    #c.sh('git config submodule."deps/sljit".url ../sljit')
    #c.sh("git -c protocol.file.allow=always submodule update")
    #c.sh("./autogen.sh")
    #the things above are needed only if you ar an idiot who uses autogenerated gh source archives!

    c.cp("deps/sljit/LICENSE", "../BSD-2-Clause.txt")
    c.sh("sed -n '70,94p' LICENCE.md > ../BSD-3-Clause.txt")
    c.sh("sed -n '100,104p' LICENCE.md > ../PCRE2-exception.txt")
    # ideally everything above is in prepare. TODO: make prepare function real!


    configure_options = [
        "--enable-jit",
        "--enable-pcre2-16",
        "--enable-pcre2-32",
        "--enable-pcre2grep-libbz2",
        "--enable-pcre2grep-libz",
        "--enable-pcre2test-libreadline",
        "--prefix=/usr",
    ]

    c.sh('export CFLAGS="$CFLAGS -ffat-lto-objects"', shell = True)
    c.sh('export CXXFLAGS="$CXXFLAGS -ffat-lto-objects"', shell = True)

    c.sh("./configure " + " ".join(configure_options))
    c.sh("make")


def install(c):
    c.sh(f"make DESTDIR={c.PKGDIR} install")
    c.sh(f"install -Dm644 ./*.txt -t {c.PKGDIR}/usr/share/licenses/{pkgname}/")
