recipever = 0
pkgname = "ca-certificates"
pkgver = "20260611"
pkgrel = 0
pkgdesc = "Common CA certificates PEM files from Mozilla"
url = "https://www.mozilla.org/en-US/about/governance/policies/security-group/certs/"
arch = "all"
license = "MPL-2.0 AND MIT"

depends = ["openssl"]
makedepends = ["perl"]

sources = [
  f"https://gitlab.alpinelinux.org/alpine/{pkgname}/-/archive/{pkgver}/{pkgname}-{pkgver}.tar.bz2",
]


def build(c):
  c.SRCDIR += f"/{pkgname}-{pkgver}"
  c.sh("make all")


def install(c):
  c.sh("make", "install", f"DESTDIR={c.PKGDIR}")

  c.sh(f"""(
    echo "# Automatically generated by {pkgname}-{pkgver}-r{pkgrel}"
    echo "# $(date)"
    echo "#"
    cd "{c.PKGDIR}/usr/share/ca-certificates/mozilla"
    find . -name '*.crt' | sort | cut -b3-
  ) > "{c.PKGDIR}/etc/ca-certificates.conf"
  """)

  c.sh(f"""(
    cd "{c.PKGDIR}/usr/share/ca-certificates/mozilla"
    find -- *.crt | sort | while read -r cert; do
      cat "$cert"
      printf "\\n"
    done
  ) > "{c.PKGDIR}/etc/ssl/certs/ca-certificates.crt"
  """)

  c.install_dir(f"{c.PKGDIR}/etc/apk/protected_paths.d")
  c.sh(f"""cat > "{c.PKGDIR}/etc/apk/protected_paths.d/ca-certificates.list" <<'EOF'
-etc/ssl/certs/ca-certificates.crt
-etc/ssl/certs/ca-cert-*.pem
-etc/ssl/certs/[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f].[r0-9]*
EOF
  """)

  c.install_dir(f"{c.PKGDIR}/etc/ca-certificates/update.d")
  c.sh(f"""cat > "{c.PKGDIR}/etc/ca-certificates/update.d/certhash" <<'EOF'
#!/bin/sh
exec /usr/bin/c_rehash /etc/ssl/certs
EOF
  """)
  c.chmod("755", f"{c.PKGDIR}/etc/ca-certificates/update.d/certhash")

  # Bundle compatibility links
  c.lnk(
    "certs/ca-certificates.crt",
    f"{c.PKGDIR}/etc/ssl/cert.pem",
    relative=True,
  )
  c.install_dir(f"{c.PKGDIR}/etc/ssl1.1")
  c.lnk("/etc/ssl/certs", f"{c.PKGDIR}/etc/ssl1.1/certs")
  c.lnk("/etc/ssl/cert.pem", f"{c.PKGDIR}/etc/ssl1.1/cert.pem")
