#!/bin/sh
export PATH="$PATH:/usr/local/bin"

mount -t devtmpfs /dev
# i do not know why but it refuses to do this shit by itself
#maybe because you dont have an init system genius
#mkdir /dev/pts /dev/shm
#mount -t devpts /dev/pts
#mount -t tmpfs /dev/shm
#mount -t proc /proc
#mount -t sysfs /sys
#mkdir /sys/fs/cgroup

#mount -t cgroup /sys/fs/cgroup
#mount -t tmpfs /run
#mount -t proc proc /proc
#mount -t sysfs sysfs /sys
#mount -t devtmpfs devtmpfs /dev
#mkdir -p /dev/pts /dev/shm
#mount -t devpts devpts /dev/pts
#mount -t tmpfs tmpfs /run

# dmesg -n 1

# figlet "Welcome to POPPYCROW LINUX"

/init_poppy
/bin/sh
